<?php

namespace PraiseItBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PrayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrayerRepository extends EntityRepository
{

}
